spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    # {cipher} prefix 를 붙여 암호화된 값이라는 걸 알려줌.
    # 대칭키 사용했을 때
    # password: "{cipher}27ffc4ea0a9b23e201b98049a0b8f361e3e0269541a52fe2d2bdbd6072fb24f3"
    # 비대칭키 사용시
    password: "{cipher}AQAM9Qk+5gR2mbwlxxtowmZdPaAiXIGaaukgqG4SPK1mD0PfcsyeSvroXhoVSBGglaJ0JXMI8n1/LGQZNKLpyGcsJWH0Q6aZ+U4UPrNnLQ9WI0K5P6lwWELJt2EEh75q3I+tAa6LIHEEjof9/ZVxJ9Xw/eYypxh8NxNUHDLbz4DS7c46Q4Q1wkNo698e+TEoF2xFeiGwNHj5ot/N3ygAb27TKrz1qpSmPI0fAwd8lfQSVmSYabNUmcTZQMJjvxQLHHSEz/d90IjxQ1PP+c3+C5fLqPxVKajKO1Fkt9cjF4xVCvlh1rvHEkjjDhi4+l+fE5/tJg1JimwSROq8ryz6iRZ9cvDAfnFlmYJPmlFhp9pen5xZwp0TNG9uutbbbzuD5UE="

order-service:
  url: "http://127.0.0.1:8000/order-service/%s/orders"
