server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: git
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          # 파일 시스템 사용
#          uri: file:///Users/ae210433/Desktop/Git/git-local-repo
          # public repository이기 때문에 인증 정보가 필요하지 않다.
          uri: https://github.com/KyeonghoYoo/Study.git
          # config 파일이 존재하는 서브 디렉토리를 기입함
          search-paths:
            - SpringCloud/configFiles
          # 가져올 config 파일이 존재하는 브랜치를 정해줌
          default-label: "#4-SpringBootCloudMicroservices"
management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, health, busrefresh