server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # 파일 시스템 사용
          uri: file:///Users/ae210433/Desktop/Git/git-local-repo